driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/sgbuild', type: "nfs"]

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
- name: centos-6_chef-11
  driver:
    box: sendgrid_centos-6_chef-11
    box_url: http://repo.sjc1.sendgrid.net/images/vagrant/metadata/sendgrid_centos-6_chef-11.json
    network:
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

suites:
  - name: default
    run_list:
      - omnibus::default
      - ci_dependencies::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/sgbuild
        install_dir: /opt/sgbuild
